name: Deploy Summarization Service to Azure VM

on:
  push:
    branches:
      - main
    paths:
      - 'Back-End/Summarization/Monolithic-Architecture/**'

jobs:
  deploy-summarization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AZURE_SUMMARIZATION_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.AZURE_SUMMARIZATION_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Summarization to Azure VM
        run: |
          ssh ${{ secrets.AZURE_SUMMARIZATION_USER }}@${{ secrets.AZURE_SUMMARIZATION_HOST }} << 'EOF'
            cd /home/azureuser/BioMentor-Personalized-E-Learning-Platform
            git pull origin main
            cd Back-End/Summarization/Monolithic-Architecture
            source venv/bin/activate
            pip install -r requirements.txt
            sudo apt-get install -y tesseract-ocr poppler-utils
            sudo systemctl restart summarize.service
          EOF
